### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yunjielu977** [scivision/h5fortran#3]
Encountered an error while making, how to solve it？
[程序问题gfortran.docx](https://github.com/scivision/h5fortran/files/4537784/gfortran.docx)

**Comment by scivision** [comment]
In your own CMakeLists.txt, you need to `find_package(HDF5 COMPONENTS Fortran HL)` and link and include HDF5 from that

**Comment by scivision** [comment]
Since HDF5 is a complex library, there are a few workarounds applied in https://github.com/scivision/h5fortran/blob/master/cmake/hdf5.cmake

so from your CMakeLIsts.txt

```cmake
include(cmake/hdf5.cmake)

target_link_libraries(hello h5fortran ${HDF5_LIBRARIES})
target_include_directories(hello PRIVATE ${HDF5_INCLUDE_DIRS})
```

**Comment by yunjielu977** [comment]
Thank you very much.
